# BlendWatch Configuration

# File extensions to watch (include the dot)
extensions = [
    ".blend",
    ".py", 
    ".txt",
    ".json",
    ".toml",
    ".yaml",
    ".yml"
]

# Directory patterns to ignore (regex patterns)
ignore_dirs = [
    "\\.git",          # Git directories
    "__pycache__",     # Python cache
    "\\.venv",         # Virtual environments
    "node_modules",    # Node.js modules
    "\\.DS_Store",     # macOS system files
    "\\.tmp"           # Temporary directories
]

# Output format: 'json' or 'text'
output_format = "json"

# Log level: 'debug', 'info', 'warning', 'error'
log_level = "info"
